### ISSUE TITLE
在 Firefox 中無法使用揚聲器收音

### ISSUE THREAD

**Issue by MDTsai** [tencentyun/TRTCSDK#517]
根據 https://github.com/webcompat/web-bugs/issues/94684 說明，在 Firefox 及 Safari 中無法使用揚聲器收音，原因是 https://github.com/tencentyun/TRTCSDK/blob/e729aec52862e7c5a6b22533559417d551c3268f/Web/base-js/js/device-testing.js#L81-L83 直接阻擋 Firefox 及 Safari

**Comment by Rychou** [comment]
您好，这是由于 Firefox 及 Safari 浏览器不支持获取扬声器列表导致的。

这个不影响用户正常使用，扬声器依然是可以正常使用的，Firefox 及 Safari 会自动选择相关的扬声器。

----

Hello, this is due to Firefox and Safari browsers do not support to get the list of speakers.

This does not affect the user's normal use, the speakers are still available, Firefox and Safari will automatically select the relevant speakers for audio output.
