### ISSUE TITLE
★【提issue必看】TRTCSDK issue 提交模板★

### ISSUE THREAD

**Issue by tao-pu** [tencentyun/TRTCSDK#53]
为了更好的了解您使用TRTCSDK所遇到的问题，方便快速有效定位解决TRTCSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题。

issue标题：

【平台】-【版本号】描述您的问题

issue内容：

【当前现象】：如进房失败，提示错误码xxxx
【集成包】：TRTC精简版 / 专业版Professional / 企业版Enterprise
【SDKAppID】：1400XXXXXX
【房间号】: 123456
【useID】：userNameA
【问题时间段】：2019-09-01 16:23~16:55
【机型】：如iPhone 7 Plus
【之前版本有无此问题】：如6.4之前没有，6.6有
【是否必现】：必现 / 偶现，
【复现方法】：如有复现方法，请说明
【日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好

-------------------------完整的示例如下：-------------------------

示例1：
【iOS】-【6.5.7272】iOS模拟器编译失败

【当前现象】：如：iOS模拟器编译失败，SDK缺模拟器版本。
【集成包】：企业版Enterprise
【SDKAppID】：N/A
【机型】：iOS 模拟器9.2，xcode版本 10.3，Mac OS 10.14.5
【之前版本有无此问题】：6.5.7272之前没有此问题
【是否必现】：必现
【日志或者截图】：暂无日志（有日志附上日志），有截图附上问题截图

示例2：
【Android】-【6.5.7272】进房失败，提示错误码XXXX

【当前现象】：如：进房失败，提示错误码xxxx
【集成包】：TRTC精简版 / 专业版Professional / 企业版Enterprise
【SDKAppID】：1400XXXXXX
【房间号】: 123456
【useID】：userNameA
【问题时间段】：2019-09-01 16:23~16:55
【机型】：如华为Mate 10
【之前版本有无此问题】：如6.5之前没有，6.5有
【是否必现】：偶现
【复现方法】：如有复现方法，请说明
【日志或者描述、截图】：如：进房失败，退房再进也无法进房成功。暂无日志（有日志附上日志），有截图附上问题截图

**Comment by zrl66** [comment]
In order to better understand the problems you meet when using TRTCSDK, and to quickly and effectively locate and solve the TRTCSDK problems, I hope you can report issues according to the following template.

Issue title:
【Platform】-【Version Number】Describe your problem

Issue content:

[Current phenomenon]: If the room fails to enter the room, the error code xxxx will be prompted.
[Integration Package]: TRTC Lite / Professional Edition / Enterprise Edition
【SDKAppID】：2000XXXXXX
【Room number】: 123456
[useID]: userNameA
[Problem time period]: 2019-09-01 16:23~16:55
【Model】: Such as iPhone 12
[Whether there is this problem in the previous version]: If there is no such problem before 6.4, there is in 6.6
[Whether it must appear]: Must appear / Occasionally appear,
[Reproduction method]: If there is a reproduction method, please explain
[Log or description, screenshot]: If there is, please attach the relevant log to facilitate our positioning, if there is a screenshot, it is better

------------------------- A complete example is as follows: -------------------- -----

Example 1:
[iOS]-[6.5.7272] Compilation failed for iOS simulator

[Current phenomenon]: For example, the iOS simulator fails to compile, and the SDK lacks the simulator version.
[Integration Package]: Enterprise Edition
【SDKAppID】：N/A
【Model】: iOS Simulator 9.2, Xcode version 10.3, Mac OS 10.14.5
[Does the previous version have this problem]: There is no such problem before 6.5.7272
[Whether it must be present]: must be present
[Log or screenshot]: There is no log at the moment (with log attached to the log), if there is a screenshot, attach the screenshot of the problem

Example 2:
[Android]-[6.5.7272] Failed to enter the room, prompting error code XXXX

[Current phenomenon]: For example: Failed to enter the room, prompt error code xxxx
[Integration Package]: TRTC Lite / Professional Edition Professional / Enterprise Edition
【SDKAppID】：2000XXXXXX
【Room number】: 123456
[useID]: userNameA
[Problem time period]: 2019-09-01 16:23~16:55
【Model】: such as Samsung Galaxy S22 
[Does the previous version have this problem]: If there is no such problem before 6.5, 6.5 has it
[Whether it must be present]: Occasionally
[Reproduction method]: If there is a reproduction method, please explain
[Log or description, screenshot]: For example: Failed to enter the room, and can not enter the room successfully after checking out. There is no log (with log attached to log), there is a screenshot attached with a screenshot of the problem

**Comment by zrl66** [comment]
In order to better understand the problems you meet when using TRTCSDK, and to quickly and effectively locate and solve the TRTCSDK problems, I hope you can report issues according to the following template.

Issue title:
【Platform】-【Version Number】Describe your problem

Issue content:

[Current phenomenon]: If fails to enter the room, the error code xxxx will be prompted.
[Integration Package]: TRTC Lite / Professional Edition
【SDKAppID】：2000XXXXXX
【Room number】: 123456
[useID]: userNameA
[Problem time period]: 2019-09-01 16:23~16:55
【Model】: Such as iPhone 12
[Whether there is this problem in the previous version]: If there is no such problem before 6.4, there is in 6.6
[Whether it must appear]: Must appear / Occasionally appear,
[Reproduction method]: If there is a reproduction method, please explain
[Log or description, screenshot]: If there is, please attach the relevant log to facilitate our positioning, if there is a screenshot, it is better

------------------------- A complete example is as follows: -------------------- -----

Example 1:
[iOS]-[6.5.7272] Compilation failed for iOS simulator

[Current phenomenon]: For example, the iOS simulator fails to compile, and the SDK lacks the simulator version.
[Integration Package]: Professional Edition
【SDKAppID】：N/A
【Model】: iOS Simulator 9.2, Xcode version 10.3, Mac OS 10.14.5
[Does the previous version have this problem]: There is no such problem before 6.5.7272
[Whether it must be present]: must be present
[Log or screenshot]: There is no log at the moment (with log attached to the log), if there is a screenshot, attach the screenshot of the problem

Example 2:
[Android]-[6.5.7272] Failed to enter the room, prompting error code XXXX

[Current phenomenon]: For example: Failed to enter the room, prompt error code xxxx
[Integration Package]: TRTC Lite / Professional Edition Professional
【SDKAppID】：2000XXXXXX
【Room number】: 123456
[useID]: userNameA
[Problem time period]: 2019-09-01 16:23~16:55
【Model】: such as Samsung Galaxy S22 
[Does the previous version have this problem]: If there is no such problem before 6.5, 6.5 has it
[Whether it must be present]: Occasionally
[Reproduction method]: If there is a reproduction method, please explain
[Log or description, screenshot]: For example: Failed to enter the room, and can not enter the room successfully after checking out. There is no log (with log attached to log), there is a screenshot attached with a screenshot of the problem.
